version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PORT: 8000  # ✅ Set it this way (key: value), not list
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn src.main:app --host 0.0.0.0 --port $PORT --reload"

